//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.34003
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.Caseberry.Logging.Objects
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    using ICSSoft.STORMNET.Business;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Application Log.
    /// </summary>
    // *** Start programmer edit section *** (ApplicationLog CustomAttributes)

    // *** End programmer edit section *** (ApplicationLog CustomAttributes)
    [BusinessServer("IIS.Caseberry.Logging.LogChanging, IIS.Caseberry.Logging.BusinessServers", ICSSoft.STORMNET.Business.DataServiceObjectEvents.OnInsertToStorage)]
    [AutoAltered()]
    [Caption("Лог приложения")]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("ApplicationLogE", new string[] {
            "Category as \'Category\'",
            "EventId as \'Event id\'",
            "Priority as \'Priority\'",
            "Severity as \'Severity\'",
            "Title as \'Title\'",
            "Timestamp as \'Timestamp\'",
            "MachineName as \'Machine name\'",
            "AppDomainName as \'App domain name\'",
            "ProcessId as \'Process id\'",
            "ProcessName as \'Process name\'",
            "ThreadName as \'Thread name\'",
            "Win32ThreadId as \'Win32 thread id\'",
            "Message as \'Message\'",
            "FormattedMessage as \'Formatted message\'"})]
    [View("ApplicationLogL", new string[] {
            "Category as \'Category\'",
            "EventId as \'Event id\'",
            "Priority as \'Priority\'",
            "Severity as \'Severity\'",
            "Title as \'Title\'",
            "Timestamp as \'Timestamp\'",
            "MachineName as \'Machine name\'",
            "AppDomainName as \'App domain name\'",
            "ProcessId as \'Process id\'",
            "ProcessName as \'Process name\'",
            "ThreadName as \'Thread name\'",
            "Win32ThreadId as \'Win32 thread id\'",
            "Message as \'Message\'",
            "FormattedMessage as \'Formatted message\'"})]
    [View("ApplicationLogRusL", new string[] {
            "Timestamp as \'Время\'",
            "Title as \'Заголовок\'",
            "Message as \'Сообщение\'",
            "FormattedMessage as \'Форматированное сообщение\'",
            "Category as \'Категория\'",
            "EventId as \'ID события\'",
            "Priority as \'Приоритет\'",
            "Severity as \'Серьёзность\'",
            "MachineName as \'Имя машины\'",
            "AppDomainName as \'Домен приложения\'",
            "ProcessId as \'ID процесса\'",
            "ProcessName as \'Имя процесса\'",
            "ThreadName as \'Имя потока\'",
            "Win32ThreadId as \'ID потока Win32\'"})]
    [View("ShortL", new string[] {
            "Timestamp as \'Время\'",
            "Title as \'Событие\'",
            "EventId as \'Код события\'",
            "Message as \'Сообщение\'",
            "Priority as \'Приоритет\'",
            "Category as \'Категория\'",
            "Severity as \'Серьёзность\'",
            "MachineName as \'Имя машины\'",
            "ProcessName as \'Имя процесса\'"})]
    public class ApplicationLog : ICSSoft.STORMNET.DataObject
    {
        
        private string fCategory;
        
        private int fEventId;
        
        private int fPriority;
        
        private string fSeverity;
        
        private string fTitle;
        
        private System.DateTime fTimestamp;
        
        private string fMachineName;
        
        private string fAppDomainName;
        
        private string fProcessId;
        
        private string fProcessName;
        
        private string fThreadName;
        
        private string fWin32ThreadId;
        
        private string fMessage;
        
        private string fFormattedMessage;
        
        // *** Start programmer edit section *** (ApplicationLog CustomMembers)
       
        /// <summary>
        /// Создать исключение, содержащее информацию по строке лога.
        /// </summary>
        /// <returns>Исключение</returns>
        public Exception CreateException()
        {
            var info = ToString();

            Exception ex;

            if (!string.IsNullOrEmpty(this.FormattedMessage))
            {
                var message = this.FormattedMessage;//.Replace("\n", "\r\n");
                ex = new ApplicationLogException(message, new Exception(info));
            }
            else
            {
                ex = new ApplicationLogException(new Exception(info));
            }

            return ex;
        }

        // *** End programmer edit section *** (ApplicationLog CustomMembers)

        
        /// <summary>
        /// Category.
        /// </summary>
        // *** Start programmer edit section *** (ApplicationLog.Category CustomAttributes)

        // *** End programmer edit section *** (ApplicationLog.Category CustomAttributes)
        [StrLen(64)]
        public virtual string Category
        {
            get
            {
                // *** Start programmer edit section *** (ApplicationLog.Category Get start)

                // *** End programmer edit section *** (ApplicationLog.Category Get start)
                string result = this.fCategory;
                // *** Start programmer edit section *** (ApplicationLog.Category Get end)

                // *** End programmer edit section *** (ApplicationLog.Category Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ApplicationLog.Category Set start)

                // *** End programmer edit section *** (ApplicationLog.Category Set start)
                this.fCategory = value;
                // *** Start programmer edit section *** (ApplicationLog.Category Set end)

                // *** End programmer edit section *** (ApplicationLog.Category Set end)
            }
        }
        
        /// <summary>
        /// EventId.
        /// </summary>
        // *** Start programmer edit section *** (ApplicationLog.EventId CustomAttributes)

        // *** End programmer edit section *** (ApplicationLog.EventId CustomAttributes)
        public virtual int EventId
        {
            get
            {
                // *** Start programmer edit section *** (ApplicationLog.EventId Get start)

                // *** End programmer edit section *** (ApplicationLog.EventId Get start)
                int result = this.fEventId;
                // *** Start programmer edit section *** (ApplicationLog.EventId Get end)

                // *** End programmer edit section *** (ApplicationLog.EventId Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ApplicationLog.EventId Set start)

                // *** End programmer edit section *** (ApplicationLog.EventId Set start)
                this.fEventId = value;
                // *** Start programmer edit section *** (ApplicationLog.EventId Set end)

                // *** End programmer edit section *** (ApplicationLog.EventId Set end)
            }
        }
        
        /// <summary>
        /// Priority.
        /// </summary>
        // *** Start programmer edit section *** (ApplicationLog.Priority CustomAttributes)

        // *** End programmer edit section *** (ApplicationLog.Priority CustomAttributes)
        public virtual int Priority
        {
            get
            {
                // *** Start programmer edit section *** (ApplicationLog.Priority Get start)

                // *** End programmer edit section *** (ApplicationLog.Priority Get start)
                int result = this.fPriority;
                // *** Start programmer edit section *** (ApplicationLog.Priority Get end)

                // *** End programmer edit section *** (ApplicationLog.Priority Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ApplicationLog.Priority Set start)

                // *** End programmer edit section *** (ApplicationLog.Priority Set start)
                this.fPriority = value;
                // *** Start programmer edit section *** (ApplicationLog.Priority Set end)

                // *** End programmer edit section *** (ApplicationLog.Priority Set end)
            }
        }
        
        /// <summary>
        /// Severity.
        /// </summary>
        // *** Start programmer edit section *** (ApplicationLog.Severity CustomAttributes)

        // *** End programmer edit section *** (ApplicationLog.Severity CustomAttributes)
        [StrLen(32)]
        public virtual string Severity
        {
            get
            {
                // *** Start programmer edit section *** (ApplicationLog.Severity Get start)

                // *** End programmer edit section *** (ApplicationLog.Severity Get start)
                string result = this.fSeverity;
                // *** Start programmer edit section *** (ApplicationLog.Severity Get end)

                // *** End programmer edit section *** (ApplicationLog.Severity Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ApplicationLog.Severity Set start)

                // *** End programmer edit section *** (ApplicationLog.Severity Set start)
                this.fSeverity = value;
                // *** Start programmer edit section *** (ApplicationLog.Severity Set end)

                // *** End programmer edit section *** (ApplicationLog.Severity Set end)
            }
        }
        
        /// <summary>
        /// Title.
        /// </summary>
        // *** Start programmer edit section *** (ApplicationLog.Title CustomAttributes)

        // *** End programmer edit section *** (ApplicationLog.Title CustomAttributes)
        [StrLen(256)]
        public virtual string Title
        {
            get
            {
                // *** Start programmer edit section *** (ApplicationLog.Title Get start)

                // *** End programmer edit section *** (ApplicationLog.Title Get start)
                string result = this.fTitle;
                // *** Start programmer edit section *** (ApplicationLog.Title Get end)

                // *** End programmer edit section *** (ApplicationLog.Title Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ApplicationLog.Title Set start)

                // *** End programmer edit section *** (ApplicationLog.Title Set start)
                this.fTitle = value;
                // *** Start programmer edit section *** (ApplicationLog.Title Set end)

                // *** End programmer edit section *** (ApplicationLog.Title Set end)
            }
        }
        
        /// <summary>
        /// Timestamp.
        /// </summary>
        // *** Start programmer edit section *** (ApplicationLog.Timestamp CustomAttributes)

        // *** End programmer edit section *** (ApplicationLog.Timestamp CustomAttributes)
        public virtual System.DateTime Timestamp
        {
            get
            {
                // *** Start programmer edit section *** (ApplicationLog.Timestamp Get start)

                // *** End programmer edit section *** (ApplicationLog.Timestamp Get start)
                System.DateTime result = this.fTimestamp;
                // *** Start programmer edit section *** (ApplicationLog.Timestamp Get end)

                // *** End programmer edit section *** (ApplicationLog.Timestamp Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ApplicationLog.Timestamp Set start)

                // *** End programmer edit section *** (ApplicationLog.Timestamp Set start)
                this.fTimestamp = value;
                // *** Start programmer edit section *** (ApplicationLog.Timestamp Set end)

                // *** End programmer edit section *** (ApplicationLog.Timestamp Set end)
            }
        }
        
        /// <summary>
        /// MachineName.
        /// </summary>
        // *** Start programmer edit section *** (ApplicationLog.MachineName CustomAttributes)

        // *** End programmer edit section *** (ApplicationLog.MachineName CustomAttributes)
        [StrLen(32)]
        public virtual string MachineName
        {
            get
            {
                // *** Start programmer edit section *** (ApplicationLog.MachineName Get start)

                // *** End programmer edit section *** (ApplicationLog.MachineName Get start)
                string result = this.fMachineName;
                // *** Start programmer edit section *** (ApplicationLog.MachineName Get end)

                // *** End programmer edit section *** (ApplicationLog.MachineName Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ApplicationLog.MachineName Set start)

                // *** End programmer edit section *** (ApplicationLog.MachineName Set start)
                this.fMachineName = value;
                // *** Start programmer edit section *** (ApplicationLog.MachineName Set end)

                // *** End programmer edit section *** (ApplicationLog.MachineName Set end)
            }
        }
        
        /// <summary>
        /// AppDomainName.
        /// </summary>
        // *** Start programmer edit section *** (ApplicationLog.AppDomainName CustomAttributes)

        // *** End programmer edit section *** (ApplicationLog.AppDomainName CustomAttributes)
        [StrLen(512)]
        public virtual string AppDomainName
        {
            get
            {
                // *** Start programmer edit section *** (ApplicationLog.AppDomainName Get start)

                // *** End programmer edit section *** (ApplicationLog.AppDomainName Get start)
                string result = this.fAppDomainName;
                // *** Start programmer edit section *** (ApplicationLog.AppDomainName Get end)

                // *** End programmer edit section *** (ApplicationLog.AppDomainName Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ApplicationLog.AppDomainName Set start)

                // *** End programmer edit section *** (ApplicationLog.AppDomainName Set start)
                this.fAppDomainName = value;
                // *** Start programmer edit section *** (ApplicationLog.AppDomainName Set end)

                // *** End programmer edit section *** (ApplicationLog.AppDomainName Set end)
            }
        }
        
        /// <summary>
        /// ProcessId.
        /// </summary>
        // *** Start programmer edit section *** (ApplicationLog.ProcessId CustomAttributes)

        // *** End programmer edit section *** (ApplicationLog.ProcessId CustomAttributes)
        [StrLen(256)]
        public virtual string ProcessId
        {
            get
            {
                // *** Start programmer edit section *** (ApplicationLog.ProcessId Get start)

                // *** End programmer edit section *** (ApplicationLog.ProcessId Get start)
                string result = this.fProcessId;
                // *** Start programmer edit section *** (ApplicationLog.ProcessId Get end)

                // *** End programmer edit section *** (ApplicationLog.ProcessId Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ApplicationLog.ProcessId Set start)

                // *** End programmer edit section *** (ApplicationLog.ProcessId Set start)
                this.fProcessId = value;
                // *** Start programmer edit section *** (ApplicationLog.ProcessId Set end)

                // *** End programmer edit section *** (ApplicationLog.ProcessId Set end)
            }
        }
        
        /// <summary>
        /// ProcessName.
        /// </summary>
        // *** Start programmer edit section *** (ApplicationLog.ProcessName CustomAttributes)

        // *** End programmer edit section *** (ApplicationLog.ProcessName CustomAttributes)
        [StrLen(512)]
        public virtual string ProcessName
        {
            get
            {
                // *** Start programmer edit section *** (ApplicationLog.ProcessName Get start)

                // *** End programmer edit section *** (ApplicationLog.ProcessName Get start)
                string result = this.fProcessName;
                // *** Start programmer edit section *** (ApplicationLog.ProcessName Get end)

                // *** End programmer edit section *** (ApplicationLog.ProcessName Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ApplicationLog.ProcessName Set start)

                // *** End programmer edit section *** (ApplicationLog.ProcessName Set start)
                this.fProcessName = value;
                // *** Start programmer edit section *** (ApplicationLog.ProcessName Set end)

                // *** End programmer edit section *** (ApplicationLog.ProcessName Set end)
            }
        }
        
        /// <summary>
        /// ThreadName.
        /// </summary>
        // *** Start programmer edit section *** (ApplicationLog.ThreadName CustomAttributes)

        // *** End programmer edit section *** (ApplicationLog.ThreadName CustomAttributes)
        [StrLen(512)]
        public virtual string ThreadName
        {
            get
            {
                // *** Start programmer edit section *** (ApplicationLog.ThreadName Get start)

                // *** End programmer edit section *** (ApplicationLog.ThreadName Get start)
                string result = this.fThreadName;
                // *** Start programmer edit section *** (ApplicationLog.ThreadName Get end)

                // *** End programmer edit section *** (ApplicationLog.ThreadName Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ApplicationLog.ThreadName Set start)

                // *** End programmer edit section *** (ApplicationLog.ThreadName Set start)
                this.fThreadName = value;
                // *** Start programmer edit section *** (ApplicationLog.ThreadName Set end)

                // *** End programmer edit section *** (ApplicationLog.ThreadName Set end)
            }
        }
        
        /// <summary>
        /// Win32ThreadId.
        /// </summary>
        // *** Start programmer edit section *** (ApplicationLog.Win32ThreadId CustomAttributes)

        // *** End programmer edit section *** (ApplicationLog.Win32ThreadId CustomAttributes)
        [StrLen(128)]
        public virtual string Win32ThreadId
        {
            get
            {
                // *** Start programmer edit section *** (ApplicationLog.Win32ThreadId Get start)

                // *** End programmer edit section *** (ApplicationLog.Win32ThreadId Get start)
                string result = this.fWin32ThreadId;
                // *** Start programmer edit section *** (ApplicationLog.Win32ThreadId Get end)

                // *** End programmer edit section *** (ApplicationLog.Win32ThreadId Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ApplicationLog.Win32ThreadId Set start)

                // *** End programmer edit section *** (ApplicationLog.Win32ThreadId Set start)
                this.fWin32ThreadId = value;
                // *** Start programmer edit section *** (ApplicationLog.Win32ThreadId Set end)

                // *** End programmer edit section *** (ApplicationLog.Win32ThreadId Set end)
            }
        }
        
        /// <summary>
        /// Message.
        /// </summary>
        // *** Start programmer edit section *** (ApplicationLog.Message CustomAttributes)

        // *** End programmer edit section *** (ApplicationLog.Message CustomAttributes)
        [StrLen(2500)]
        public virtual string Message
        {
            get
            {
                // *** Start programmer edit section *** (ApplicationLog.Message Get start)

                // *** End programmer edit section *** (ApplicationLog.Message Get start)
                string result = this.fMessage;
                // *** Start programmer edit section *** (ApplicationLog.Message Get end)

                // *** End programmer edit section *** (ApplicationLog.Message Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ApplicationLog.Message Set start)

                // *** End programmer edit section *** (ApplicationLog.Message Set start)
                this.fMessage = value;
                // *** Start programmer edit section *** (ApplicationLog.Message Set end)

                // *** End programmer edit section *** (ApplicationLog.Message Set end)
            }
        }
        
        /// <summary>
        /// FormattedMessage.
        /// </summary>
        // *** Start programmer edit section *** (ApplicationLog.FormattedMessage CustomAttributes)

        // *** End programmer edit section *** (ApplicationLog.FormattedMessage CustomAttributes)
        public virtual string FormattedMessage
        {
            get
            {
                // *** Start programmer edit section *** (ApplicationLog.FormattedMessage Get start)

                // *** End programmer edit section *** (ApplicationLog.FormattedMessage Get start)
                string result = this.fFormattedMessage;
                // *** Start programmer edit section *** (ApplicationLog.FormattedMessage Get end)

                // *** End programmer edit section *** (ApplicationLog.FormattedMessage Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ApplicationLog.FormattedMessage Set start)

                // *** End programmer edit section *** (ApplicationLog.FormattedMessage Set start)
                this.fFormattedMessage = value;
                // *** Start programmer edit section *** (ApplicationLog.FormattedMessage Set end)

                // *** End programmer edit section *** (ApplicationLog.FormattedMessage Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "ApplicationLogE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ApplicationLogE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ApplicationLogE", typeof(IIS.Caseberry.Logging.Objects.ApplicationLog));
                }
            }
            
            /// <summary>
            /// "ApplicationLogL" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ApplicationLogL
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ApplicationLogL", typeof(IIS.Caseberry.Logging.Objects.ApplicationLog));
                }
            }
            
            /// <summary>
            /// "ApplicationLogRusL" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ApplicationLogRusL
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ApplicationLogRusL", typeof(IIS.Caseberry.Logging.Objects.ApplicationLog));
                }
            }
            
            /// <summary>
            /// "ShortL" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ShortL
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ShortL", typeof(IIS.Caseberry.Logging.Objects.ApplicationLog));
                }
            }
        }
    }
}
