//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.225
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.Caseberry.Logging.MsEntLib.Configuration {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class DesignResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal DesignResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("IIS.Caseberry.Logging.MsEntLib.Configuration.DesignResources", typeof(DesignResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A logging target listener that sends log messages to a specified database using a database instance configured in the Data Access Application Block..
        /// </summary>
        internal static string CaseberryDatabaseTraceListenerDataDescription {
            get {
                return ResourceManager.GetString("CaseberryDatabaseTraceListenerDataDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Database Trace Listener.
        /// </summary>
        internal static string CaseberryDatabaseTraceListenerDataDisplayName {
            get {
                return ResourceManager.GetString("CaseberryDatabaseTraceListenerDataDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The minimum severity of messages that will be sent to the logging target. 
        ///Valid values are All (the default), Off, Critical, Error, Warning, Information, Verbose, and Activity Tracing. 
        ///The behavior is for messages with the selected severity and all higher severities to be included. 
        ///For example, the Warning setting will allow warning, error, and critical messages to be written to the logging target..
        /// </summary>
        internal static string CaseberryDatabaseTraceListenerDataFilterDescription {
            get {
                return ResourceManager.GetString("CaseberryDatabaseTraceListenerDataFilterDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Severity Filter.
        /// </summary>
        internal static string CaseberryDatabaseTraceListenerDataFilterDisplayName {
            get {
                return ResourceManager.GetString("CaseberryDatabaseTraceListenerDataFilterDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The name of the Log Message Formatter to use to format log messages written to the database..
        /// </summary>
        internal static string CaseberryDatabaseTraceListenerDataFormatterDescription {
            get {
                return ResourceManager.GetString("CaseberryDatabaseTraceListenerDataFormatterDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Formatter.
        /// </summary>
        internal static string CaseberryDatabaseTraceListenerDataFormatterDisplayName {
            get {
                return ResourceManager.GetString("CaseberryDatabaseTraceListenerDataFormatterDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The fully qualified type name of the Listener..
        /// </summary>
        internal static string CaseberryDatabaseTraceListenerDataListenerDataTypeNameDescription {
            get {
                return ResourceManager.GetString("CaseberryDatabaseTraceListenerDataListenerDataTypeNameDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Listener Data Type.
        /// </summary>
        internal static string CaseberryDatabaseTraceListenerDataListenerDataTypeNameDisplayName {
            get {
                return ResourceManager.GetString("CaseberryDatabaseTraceListenerDataListenerDataTypeNameDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The name of the Database Trace Listener..
        /// </summary>
        internal static string CaseberryDatabaseTraceListenerDataNameDescription {
            get {
                return ResourceManager.GetString("CaseberryDatabaseTraceListenerDataNameDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        internal static string CaseberryDatabaseTraceListenerDataNameDisplayName {
            get {
                return ResourceManager.GetString("CaseberryDatabaseTraceListenerDataNameDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Listeners that do not output to a Text Formatter use this property to determine which options, or elements, should be included in the trace output. 
        ///Possible values are: CallStack, DateTime, LogicalOperationStack, None, ProcessId, ThreadId, and Timestamp. The default is None. This property is optional..
        /// </summary>
        internal static string CaseberryDatabaseTraceListenerDataTraceOutputOptionsDescription {
            get {
                return ResourceManager.GetString("CaseberryDatabaseTraceListenerDataTraceOutputOptionsDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trace Output Options.
        /// </summary>
        internal static string CaseberryDatabaseTraceListenerDataTraceOutputOptionsDisplayName {
            get {
                return ResourceManager.GetString("CaseberryDatabaseTraceListenerDataTraceOutputOptionsDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The fully qualified type name of the Database Trace Listener..
        /// </summary>
        internal static string CaseberryDatabaseTraceListenerDataTypeNameDescription {
            get {
                return ResourceManager.GetString("CaseberryDatabaseTraceListenerDataTypeNameDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type.
        /// </summary>
        internal static string CaseberryDatabaseTraceListenerDataTypeNameDisplayName {
            get {
                return ResourceManager.GetString("CaseberryDatabaseTraceListenerDataTypeNameDisplayName", resourceCulture);
            }
        }
    }
}
