//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:2.0.50727.5420
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

using ICSSoft.STORMNET;

namespace IIS.Caseberry.Logging
{
    using Unity;
    using ICSSoft.Services;
    using IIS.Caseberry.Logging.Objects;

    // *** Start programmer edit section *** (LogChanging CustomAttributes)

    // *** End programmer edit section *** (LogChanging CustomAttributes)
    [ICSSoft.STORMNET.AccessType(ICSSoft.STORMNET.AccessType.none)]
    public class LogChanging : ICSSoft.STORMNET.Business.BusinessServer
    {

        // *** Start programmer edit section *** (LogChanging CustomMembers)
        private ILogManager _logManager;

        /// <summary>
        /// Получение инстации лог менеджера.
        /// </summary>
        protected ILogManager LogManager
        {
            get
            {
                if (_logManager != null)
                {
                    return _logManager;
                }

                IUnityContainer container = UnityFactory.GetContainer();
                _logManager = container.Resolve<ILogManager>();

                return _logManager;
            }
        }
        // *** End programmer edit section *** (LogChanging CustomMembers)


        public virtual ICSSoft.STORMNET.DataObject[] OnUpdateApplicationLog(Objects.ApplicationLog UpdatedObject)
        {
            // *** Start programmer edit section *** (OnUpdateApplicationLog)

            if (UpdatedObject.GetStatus() == ObjectStatus.Created)
            {
                LogManager.OnNewLogEntryAdded(new DataObjectIdEventArgs
                {
                    DataObjectId = UpdatedObject.__PrimaryKey
                });
            }

            return new ICSSoft.STORMNET.DataObject[] { UpdatedObject };
            // *** End programmer edit section *** (OnUpdateApplicationLog)
        }
    }
}
